// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://czqhorgsutnadznkibkb.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImN6cWhvcmdzdXRuYWR6bmtpYmtiIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NzI0NzI2MjEsImV4cCI6MjA4ODA0ODYyMX0.WViPv1e2TjqZEiKuXjaVt4UuYJ-r6GLgxfBOg0lxm4I";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});